branches = ["develop"]

[[plugins]]
plugin = "@semantic-release/commit-analyzer"

[[plugins]]
plugin = "@semantic-release/release-notes-generator"

[[plugins]]
plugin = "@semantic-release/changelog"

[[plugins]]
plugin = "semantic-release-exec"
prepareCmd = "pre-commit run --all-files"

[[plugins]]
plugin = "@semantic-release/github"

[[plugins]]
plugin = "@semantic-release/git"
assets = ["CHANGELOG.md"]
message = "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
